import { mkdir, writeFile } from 'fs/promises';
import { resolve } from 'path';
import type { Config } from 'utils/config';
import logger from 'utils/logger';

export const generateNextPlatform = async (config: Config) => {
  // TODO: This doesn't support REST right now, we should figure out how to best-support REST. This
  // is 100% on the roadmap but currently not relevant for our own internal products
  const handlerOutput = `//
// Autogenerated by \`@antribute/backend-cli\`
// Any modifications will be overwritten on subsequent runs.
//

import { createYoga } from 'graphql-yoga'
import { NextResponse } from 'next/server';
import schema from '../schema';

const apiCatchAll = async (request: Request) => {
  const yogaServer = createYoga<Request, {}>({ graphqlEndpoint: '/api/graphql', schema })(request, NextResponse)

  return yogaServer
}

export async function GET(request: Request) {
  return apiCatchAll(request);
}

export async function POST(request: Request) {
  return apiCatchAll(request);
}
`;

  const nextDir = resolve(process.cwd(), config.serverDir, 'generated', 'nextjs');
  logger.debug(
    `Creating Next.js handler directory (if it doesn't already exist) at ${nextDir}`,
    config
  );
  await mkdir(nextDir, { recursive: true });
  const nextFile = resolve(nextDir, 'index.ts');
  logger.debug(`Writing Next.js handler to ${nextFile}`, config);
  await writeFile(nextFile, handlerOutput);

  logger.info('Next.js Platform Successfully Updated', config);
};

export const generatePlatform = async (config: Config) => {
  switch (config.platform) {
    case 'express':
      logger.debug('Selected Platform: Express.js', config);
      logger.warn(
        'Express.js platform is not currently supported, please try again in future versions',
        config
      );
      break;
    case 'nextjs':
      logger.debug('Selected Platform: Next.js', config);
      await generateNextPlatform(config);
      break;
    default:
      // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
      throw new Error(`Invalid Platform ${config.platform}`);
  }
};
