export interface NextHandlerTemplate {
  useGraphql: boolean;
}
export const nextHandlerTemplate = `//
// Autogenerated by \`@antribute/backend-cli\`
// Any modifications will be overwritten on subsequent runs.
//

import { NextResponse } from 'next/server';
{{#if useGraphql}}
import { useDisableIntrospection } from '@graphql-yoga/plugin-disable-introspection'
import { createYoga } from 'graphql-yoga'
import schema from '../graphqlSchema';
{{/if}}

interface Ctx {
  params: {
    path: string[];
  };
}

{{#if useGraphql}}
const yoga = createYoga({
  graphiql: process.env.NODE_ENV !== 'production',
  plugins: process.env.NODE_ENV !== 'production' ? [useDisableIntrospection()] : [],
  graphqlEndpoint: '/api/graphql',
  schema,
});
{{/if}}

export async function apiCatchAll(request: Request, { params }: Ctx) {
  {{#if useGraphql}}
  if (params.path?.[0] === 'graphql') {
    const yogaRes = await yoga.fetch(request);
    return new NextResponse(yogaRes.body, yogaRes);
  }
  return NextResponse.json({ errors: [{ message: 'Not found.' }] }, { status: 404 });
  {{/if}}
}

export async function GET(request: Request, ctx: Ctx) {
  return apiCatchAll(request, ctx);
}

export async function POST(request: Request, ctx: Ctx) {
  return apiCatchAll(request, ctx);
}
`;
