//
// Autogenerated by `@antribute/backend-cli`
// This is only generated on first run, so be careful while
// modifying as Antribute Backend requires these exports
//

import { PrismaAdapter } from '@next-auth/prisma-adapter';
import type { AuthOptions } from 'next-auth';

import { prisma } from '../generated/db';

export const adapter = PrismaAdapter(prisma);
export const providers: AuthOptions['providers'] = [
  /* TODO: Add your providers here! */
];
