/* eslint-disable tailwindcss/no-custom-classname */
import clsx from 'clsx';

export const colorVariants = {
  text: {
    primary: clsx('text-primary'),
    neutral: clsx('text-neutral-300 dark:text-neutral-300'),
    inverse: clsx('text-surface-inverse-50 dark:text-surface-50'),
    positive: clsx('text-positive'),
    danger: clsx('text-danger'),
    caution: clsx('text-caution'),
    surface: clsx('text-content-moderate dark:text-content-inverse-moderate'),
    'various-blue': clsx('text-various-blue'),
    'various-emerald': clsx('text-various-emerald'),
    'various-orange': clsx('text-various-orange'),
    'various-fuchsia': clsx('text-various-fuchsia'),
    'various-yellow': clsx('text-various-yellow'),
    'various-rose': clsx('text-various-rose'),
    'various-cyan': clsx('text-various-cyan'),
    'various-violet': clsx('text-various-violet'),
    'various-teal': clsx('text-various-teal'),
    'various-pink': clsx('text-various-pink'),
    'various-lime': clsx('text-various-lime'),
    'various-gray': clsx('text-various-gray'),
  },
  textBgContrast: {
    primary: clsx('text-content-inverse-intense'),
    neutral: clsx('text-content-inverse-intense'),
    inverse: clsx('text-content-inverse-intense dark:text-surface-inverse-50'),
    positive: clsx('text-content-inverse-intense'),
    danger: clsx('text-content-inverse-intense'),
    caution: clsx('text-content-inverse-intense'),
    surface: clsx('text-content-moderate dark:text-content-inverse-intense'),
    'various-blue': clsx('text-content-inverse-intense'),
    'various-emerald': clsx('text-content-inverse-intense'),
    'various-orange': clsx('text-content-inverse-intense'),
    'various-fuchsia': clsx('text-content-inverse-intense'),
    'various-yellow': clsx('text-content-inverse-intense'),
    'various-rose': clsx('text-content-inverse-intense'),
    'various-cyan': clsx('text-content-inverse-intense'),
    'various-violet': clsx('text-content-inverse-intense'),
    'various-teal': clsx('text-content-inverse-intense'),
    'various-pink': clsx('text-content-inverse-intense'),
    'various-lime': clsx('text-content-inverse-intense'),
    'various-gray': clsx('text-content-inverse-intense'),
  },
  bg: {
    primary: clsx('bg-primary'),
    neutral: clsx('bg-neutral-600'),
    positive: clsx('bg-positive'),
    danger: clsx('bg-danger'),
    caution: clsx('bg-caution'),
    inverse: clsx('bg-neutral-900', 'dark:bg-content-inverse-intense'),
    surface: clsx('bg-surface dark:bg-surface-inverse-100'),
    'surface-soft': clsx('bg-surface-soft', 'dark:bg-surface-inverse-soft'),
    'surface-light': clsx('bg-surface-light', 'dark:bg-surface-inverse-light'),
    'surface-dark': clsx('bg-surface-dark', 'dark:bg-surface-inverse-dark'),
    'various-blue': clsx('bg-various-blue'),
    'various-emerald': clsx('bg-various-emerald'),
    'various-orange': clsx('bg-various-orange'),
    'various-fuchsia': clsx('bg-various-fuchsia'),
    'various-yellow': clsx('bg-various-yellow'),
    'various-rose': clsx('bg-various-rose'),
    'various-cyan': clsx('bg-various-cyan'),
    'various-violet': clsx('bg-various-violet'),
    'various-teal': clsx('bg-various-teal'),
    'various-pink': clsx('bg-various-pink'),
    'various-lime': clsx('bg-various-lime'),
    'various-gray': clsx('bg-various-gray'),
  },
  bgHighlight: {
    primary: clsx('bg-primary-light/10'),
    neutral: clsx('bg-neutral-400/10'),
    positive: clsx('bg-positive-light/10'),
    danger: clsx('bg-danger-light/10'),
    caution: clsx('bg-caution-light/10'),
    'various-blue': clsx('bg-various-blue-light/10'),
    'various-emerald': clsx('bg-various-emerald-light/10'),
    'various-orange': clsx('bg-various-orange-light/10'),
    'various-fuchsia': clsx('bg-various-fuchsia-light/10'),
    'various-yellow': clsx('bg-various-yellow-light/10'),
    'various-rose': clsx('bg-various-rose-light/10'),
    'various-cyan': clsx('bg-various-cyan-light/10'),
    'various-violet': clsx('bg-various-violet-light/10'),
    'various-teal': clsx('bg-various-teal-light/10'),
    'various-pink': clsx('bg-various-pink-light/10'),
    'various-lime': clsx('bg-various-lime-light/10'),
    'various-gray': clsx('bg-various-gray-light/10'),
    inverse: clsx('bg-surface-inverse/10', 'dark:bg-surface/10'),
    surface: clsx('bg-surface/10', 'dark:bg-surface-inverse-50/30'),
  },
  bgHoverHighlightDark: {
    primary: clsx('hover:bg-primary-light/20'),
    neutral: clsx('hover:bg-neutral-400/20'),
    positive: clsx('hover:bg-positive-light/20'),
    danger: clsx('hover:bg-danger-light/20'),
    caution: clsx('hover:bg-caution-light/20'),
    'various-blue': clsx('hover:bg-various-blue-light/20'),
    'various-emerald': clsx('hover:bg-various-emerald-light/20'),
    'various-orange': clsx('hover:bg-various-orange-light/20'),
    'various-fuchsia': clsx('hover:bg-various-fuchsia-light/20'),
    'various-yellow': clsx('hover:bg-various-yellow-light/20'),
    'various-rose': clsx('hover:bg-various-rose-light/20'),
    'various-cyan': clsx('hover:bg-various-cyan-light/20'),
    'various-violet': clsx('hover:bg-various-violet-light/20'),
    'various-teal': clsx('hover:bg-various-teal-light/20'),
    'various-pink': clsx('hover:bg-various-pink-light/20'),
    'various-lime': clsx('hover:bg-various-lime-light/20'),
    'various-gray': clsx('hover:bg-various-gray-light/20'),
    inverse: clsx('hover:bg-surface-inverse/20', 'dark:hover:bg-surface/20'),
    surface: clsx('hover:bg-surface/20', 'dark:hover:bg-surface-inverse-soft/20'),
  },
  hoverDark: {
    primary: clsx('hover:bg-primary-dark'),
    neutral: clsx('hover:bg-neutral-600'),
    positive: clsx('hover:bg-positive-dark'),
    danger: clsx('hover:bg-danger-dark'),
    caution: clsx('hover:bg-caution-dark'),
    inverse: clsx('hover:bg-surface-inverse-dark dark:hover:bg-surface-dark'),
    surface: clsx('hover:bg-surface-100 hover:dark:bg-surface-inverse-400'),
    'surface-soft': clsx('hover:bg-surface-light', 'hover:dark:bg-surface-inverse-light'),
    'surface-light': clsx('hover:bg-surface-dark', 'hover:dark:bg-surface-inverse-dark'),
    'surface-dark': clsx('hover:bg-surface-900', 'hover:dark:bg-surface-inverse-900'),
    'various-blue': clsx('hover:bg-various-blue-dark'),
    'various-emerald': clsx('hover:bg-various-emerald-dark'),
    'various-orange': clsx('hover:bg-various-orange-dark'),
    'various-fuchsia': clsx('hover:bg-various-fuchsia-dark'),
    'various-yellow': clsx('hover:bg-various-yellow-dark'),
    'various-rose': clsx('hover:bg-various-rose-dark'),
    'various-cyan': clsx('hover:bg-various-cyan-dark'),
    'various-violet': clsx('hover:bg-various-violet-dark'),
    'various-teal': clsx('hover:bg-various-teal-dark'),
    'various-pink': clsx('hover:bg-various-pink-dark'),
    'various-lime': clsx('hover:bg-various-lime-dark'),
    'various-gray': clsx('hover:bg-various-gray-dark'),
  },
  border: {
    primary: clsx('border-primary'),
    neutral: clsx('border-neutral'),
    positive: clsx('border-positive'),
    danger: clsx('border-danger'),
    caution: clsx('border-caution'),
    surface: clsx('border-black/20 dark:border-white/20'),
    inverse: clsx('border-black/10 dark:border-white/60'),
    'various-blue': clsx('border-various-blue'),
    'various-emerald': clsx('border-various-emerald'),
    'various-orange': clsx('border-various-orange'),
    'various-fuchsia': clsx('border-various-fuchsia'),
    'various-yellow': clsx('border-various-yellow'),
    'various-rose': clsx('border-various-rose'),
    'various-cyan': clsx('border-various-cyan'),
    'various-violet': clsx('border-various-violet'),
    'various-teal': clsx('border-various-teal'),
    'various-pink': clsx('border-various-pink'),
    'various-lime': clsx('border-various-lime'),
    'various-gray': clsx('border-various-gray'),
  },
  focusBorder: {
    neutral: clsx('focus:border-neutral-light'),
    primary: clsx('focus:border-primary-light'),
    positive: clsx('focus:border-positive-light'),
    danger: clsx('focus:border-danger-light'),
    caution: clsx('focus:border-caution-light'),
    inverse: clsx('focus:border-surface-inverse dark:focus:border-surface'),
    surface: clsx(''),
    'various-blue': clsx('focus:border-various-blue'),
    'various-emerald': clsx('focus:border-various-emerald'),
    'various-orange': clsx('focus:border-various-orange'),
    'various-fuchsia': clsx('focus:border-various-fuchsia'),
    'various-yellow': clsx('focus:border-various-yellow'),
    'various-rose': clsx('focus:border-various-rose'),
    'various-cyan': clsx('focus:border-various-cyan'),
    'various-violet': clsx('focus:border-various-violet'),
    'various-teal': clsx('focus:border-various-teal'),
    'various-pink': clsx('focus:border-various-pink'),
    'various-lime': clsx('focus:border-various-lime'),
    'various-gray': clsx('focus:border-various-gray'),
  },
  focusRing: {
    neutral: clsx('focus:ring-neutral'),
    primary: clsx('focus:ring-primary'),
    positive: clsx('focus:ring-positive'),
    danger: clsx('focus:ring-danger'),
    caution: clsx('focus:ring-caution'),
    surface: clsx('focus:ring-black/10 dark:focus:ring-white/10'),
    inverse: clsx('focus:ring-surface-inverse dark:focus:ring-surface'),
    'various-blue': clsx('focus:ring-various-blue'),
    'various-emerald': clsx('focus:ring-various-emerald'),
    'various-orange': clsx('focus:ring-various-orange'),
    'various-fuchsia': clsx('focus:ring-various-fuchsia'),
    'various-yellow': clsx('focus:ring-various-yellow'),
    'various-rose': clsx('focus:ring-various-rose'),
    'various-cyan': clsx('focus:ring-various-cyan'),
    'various-violet': clsx('focus:ring-various-violet'),
    'various-teal': clsx('focus:ring-various-teal'),
    'various-pink': clsx('focus:ring-various-pink'),
    'various-lime': clsx('focus:ring-various-lime'),
    'various-gray': clsx('focus:ring-various-gray'),
  },
  ring: {
    neutral: clsx('ring-neutral-300 dark:ring-neutral-400'),
    primary: clsx('ring-primary'),
    positive: clsx('ring-positive'),
    danger: clsx('ring-danger'),
    caution: clsx('ring-caution'),
    surface: clsx('ring-black/10 dark:ring-surface-inverse-200'),
    inverse: clsx('ring-surface-inverse dark:ring-surface'),
    'various-blue': clsx('ring-various-blue'),
    'various-emerald': clsx('ring-various-emerald'),
    'various-orange': clsx('ring-various-orange'),
    'various-fuchsia': clsx('ring-various-fuchsia'),
    'various-yellow': clsx('ring-various-yellow'),
    'various-rose': clsx('ring-various-rose'),
    'various-cyan': clsx('ring-various-cyan'),
    'various-violet': clsx('ring-various-violet'),
    'various-teal': clsx('ring-various-teal'),
    'various-pink': clsx('ring-various-pink'),
    'various-lime': clsx('ring-various-lime'),
    'various-gray': clsx('ring-various-gray'),
  },
  fill: {
    primary: clsx('fill-primary'),
    neutral: clsx('fill-neutral'),
    'neutral-light': clsx('fill-neutral-light'),
    positive: clsx('fill-positive'),
    danger: clsx('fill-danger'),
    caution: clsx('fill-caution'),
    inverse: clsx('fill-surface-inverse', 'dark:fill-surface'),
    surface: clsx('fill-surface', 'dark:fill-surface-inverse-soft'),
    'surface-soft': clsx('fill-surface-soft', 'dark:fill-surface-inverse-soft'),
    'surface-light': clsx('fill-surface-light', 'dark:fill-surface-inverse-light'),
    'surface-dark': clsx('fill-surface-dark', 'dark:fill-surface-inverse-dark'),
    'various-blue': clsx('fill-various-blue'),
    'various-emerald': clsx('fill-various-emerald'),
    'various-orange': clsx('fill-various-orange'),
    'various-fuchsia': clsx('fill-various-fuchsia'),
    'various-yellow': clsx('fill-various-yellow'),
    'various-rose': clsx('fill-various-rose'),
    'various-cyan': clsx('fill-various-cyan'),
    'various-violet': clsx('fill-various-violet'),
    'various-teal': clsx('fill-various-teal'),
    'various-pink': clsx('fill-various-pink'),
    'various-lime': clsx('fill-various-lime'),
    'various-gray': clsx('fill-various-gray'),
    transparent: clsx('fill-transparent'),
  },
  shadow: {
    primary: clsx('shadow-primary/50', 'dark:shadow-primary-800/60'),
    neutral: clsx('shadow-neutral-500/50', 'dark:shadow-neutral-800/80'),
    positive: clsx('shadow-positive/50', 'dark:shadow-positive-800/60'),
    danger: clsx('shadow-danger/50', 'dark:shadow-danger-800/60'),
    caution: clsx('shadow-caution/50', 'dark:shadow-caution-800/60'),
    inverse: clsx('shadow-surface-inverse/50', 'dark:shadow-surface-inverse-50/80'),
    surface: clsx('shadow-surface-800', 'dark:shadow-neutral-800/80'),
    'surface-soft': clsx('shadow-surface-soft/50', 'dark:shadow-surface-soft/60'),
    'surface-light': clsx('shadow-surface-light/50', 'dark:shadow-surface-light/60'),
    'surface-dark': clsx('shadow-surface-dark/50', 'dark:shadow-surface-dark/60'),
    'various-blue': clsx('shadow-various-blue/50', 'dark:shadow-various-blue-800/60'),
    'various-emerald': clsx('shadow-various-emerald/50', 'dark:shadow-various-emerald-800/60'),
    'various-orange': clsx('shadow-various-orange/50', 'dark:shadow-various-orange-800/60'),
    'various-fuchsia': clsx('shadow-various-fuchsia/50', 'dark:shadow-various-fuchsia-800/60'),
    'various-yellow': clsx('shadow-various-yellow/50', 'dark:shadow-various-yellow-800/60'),
    'various-rose': clsx('shadow-various-rose/50', 'dark:shadow-various-rose-800/60'),
    'various-cyan': clsx('shadow-various-cyan/50', 'dark:shadow-various-cyan-800/60'),
    'various-violet': clsx('shadow-various-violet/50', 'dark:shadow-various-violet-800/60'),
    'various-teal': clsx('shadow-various-teal/50', 'dark:shadow-various-teal-800/60'),
    'various-pink': clsx('shadow-various-pink/50', 'dark:shadow-various-pink-800/60'),
    'various-lime': clsx('shadow-various-lime/50', 'dark:shadow-various-lime-800/60'),
    'various-gray': clsx('shadow-various-gray/50', 'dark:shadow-various-gray-800/60'),
  },

  gradient: {
    primary: clsx('from-primary-300 via-primary-500  to-primary-700'),
    neutral: clsx(
      'from-neutral-300 via-neutral-400  to-neutral-700',
      'dark:from-neutral-300 dark:via-neutral-600  dark:to-surface-inverse'
    ),
    positive: clsx('from-positive-300 via-positive-500  to-positive-700'),
    danger: clsx('from-danger-300 via-danger-500  to-danger-600'),
    caution: clsx('from-caution-300 via-caution-500  to-caution-600'),
    'various-blue': clsx('from-various-blue-300 via-various-blue-500  to-various-blue-600'),
    'various-emerald': clsx(
      'from-various-emerald-300 via-various-emerald-500  to-various-emerald-600'
    ),
    'various-orange': clsx('from-various-orange-300 via-various-orange-500  to-various-orange-600'),
    'various-fuchsia': clsx(
      'from-various-fuchsia-300 via-various-fuchsia-500  to-various-fuchsia-600'
    ),
    'various-yellow': clsx('from-various-yellow-300 via-various-yellow-500  to-various-yellow-600'),
    'various-rose': clsx('from-various-rose-300 via-various-rose-500  to-various-rose-600'),
    'various-cyan': clsx('from-various-cyan-300 via-various-cyan-500  to-various-cyan-600'),
    'various-violet': clsx('from-various-violet-300 via-various-violet-500  to-various-violet-600'),
    'various-teal': clsx('from-various-teal-300 via-various-teal-500  to-various-teal-600'),
    'various-pink': clsx('from-various-pink-300 via-various-pink-500  to-various-pink-600'),
    'various-lime': clsx('from-various-lime-300 via-various-lime-500  to-various-lime-600'),
    'various-gray': clsx('from-various-gray-300 via-various-gray-500  to-various-gray-600'),

    inverse: clsx(
      'from-neutral-300 to-surface-inverse',
      'dark:from-surface-50  dark:to-neutral-400 '
    ),
    surface: clsx(
      'from-surface-50  via-surface-200 to-surface-900',
      'dark:from-neutral-500 dark:via-surface-inverse-300 dark:to-surface-inverse-900'
    ),
    'surface-soft': clsx(
      'from-surface-soft',
      'dark:from-surface-inverse-soft dark:to-surface-inverse-soft'
    ),
    'surface-light': clsx(
      'from-surface-light',
      'dark:from-surface-inverse-light dark:to-surface-inverse-light'
    ),
    'surface-dark': clsx(
      'from-surface-dark',
      'dark:from-surface-inverse-dark dark:to-surface-inverse-dark'
    ),
  },
};

export const colorToTWTokenMap = {
  neutral: 'neutral',
  blue: 'various-blue',
  green: 'various-emerald',
  red: 'various-red',
  yellow: 'various-yellow',
  orange: 'various-orange',
  fuchsia: 'various-fuchsia',
  rose: 'various-rose',
  cyan: 'various-cyan',
  violet: 'various-violet',
  teal: 'various-teal',
  pink: 'various-pink',
  lime: 'various-lime',
  gray: 'various-gray',
};
