import clsx from 'clsx';

export const colorVariants = {
  text: {
    primary: clsx('text-primary'),
    secondary: clsx('text-secondary'),
    positive: clsx('text-positive'),
    danger: clsx('text-danger'),
    caution: clsx('text-caution'),
    weak: clsx('text-content dark:text-content-inverse-weak'),
    moderate: clsx('text-content-weak dark:text-content-inverse-moderate'),
    strong: clsx('text-content-strong dark:text-content-inverse-strong'),
  },
  bg: {
    // inverse: clsx('bg-content-moderate', 'dark:bg-content-inverse-strong'),
    primary: clsx('bg-primary'),
    secondary: clsx('bg-secondary'),
    positive: clsx('bg-positive'),
    danger: clsx('bg-danger'),
    caution: clsx('bg-caution'),
    surface: clsx('bg-surface-soft', 'dark:bg-surface-inverse-soft'),
    'surface-soft': clsx('bg-surface-soft', 'dark:bg-surface-inverse-soft'),
    'surface-light': clsx('bg-surface-light', 'dark:bg-surface-inverse-light'),
    'surface-dark': clsx('bg-surface-dark', 'dark:bg-surface-inverse-dark'),
  },
  hoverDark: {
    primary: clsx('hover:bg-primary-dark'),
    secondary: clsx('hover:bg-secondary-dark'),
    positive: clsx('hover:bg-positive-dark'),
    danger: clsx('hover:bg-danger-dark'),
    caution: clsx('hover:bg-caution-dark'),
    surface: clsx('bg-surface dark:bg-surface-inverse'),
    'surface-soft': clsx('bg-surface-light dark:bg-surface-inverse-light'),
    'surface-light': clsx('bg-surface-dark dark:bg-surface-inverse-dark'),
    'surface-dark': clsx('bg-surface-900 dark:bg-surface-inverse-900'),
  },
  border: {
    primary: clsx('border-primary'),
    secondary: clsx('border-secondary'),
    positive: clsx('border-positive'),
    danger: clsx('border-danger'),
    caution: clsx('border-caution'),
    surface: clsx('border-surface dark:border-surface-inverse'),
    'surface-soft': clsx('border-surface-soft dark:border-surface-inverse-soft'),
    'surface-light': clsx('border-surface-light dark:border-surface-inverse-light'),
    'surface-dark': clsx('border-surface-dark dark:border-surface-inverse-dark'),
  },
};
