import clsx from 'clsx';

export const colorVariants = {
  text: {
    primary: clsx('text-content-intense dark:text-content-inverse-intense'),
    neutral: clsx('text-content-intense dark:text-content-inverse-intense'),
    info: clsx('text-info'),
    positive: clsx('text-positive'),
    danger: clsx('text-danger'),
    caution: clsx('text-caution'),
    surface: clsx('text-content-moderate dark:text-content-inverse-moderate'),
    'various-blue': clsx('text-various-blue'),
    'various-emerald': clsx('text-various-emerald'),
    'various-orange': clsx('text-various-orange'),
    'various-fuchsia': clsx('text-various-fuchsia'),
    'various-yellow': clsx('text-various-yellow'),
    'various-rose': clsx('text-various-rose'),
    'various-cyan': clsx('text-various-cyan'),
    'various-violet': clsx('text-various-violet'),
    'various-teal': clsx('text-various-teal'),
    'various-pink': clsx('text-various-pink'),
    'various-lime': clsx('text-various-lime'),
    'various-gray': clsx('text-various-gray'),
  },
  bg: {
    inverse: clsx('bg-surface-inverse', 'dark:bg-surface'),
    primary: clsx('bg-neutral'),
    neutral: clsx('bg-neutral'),
    info: clsx('bg-info'),
    positive: clsx('bg-positive'),
    danger: clsx('bg-danger'),
    caution: clsx('bg-caution'),
    surface: clsx('bg-surface', 'dark:bg-surface-inverse-soft'),
    'surface-soft': clsx('bg-surface-soft', 'dark:bg-surface-inverse-soft'),
    'surface-light': clsx('bg-surface-light', 'dark:bg-surface-inverse-light'),
    'surface-dark': clsx('bg-surface-dark', 'dark:bg-surface-inverse-dark'),
    'various-blue': clsx('bg-various-blue'),
    'various-emerald': clsx('bg-various-emerald'),
    'various-orange': clsx('bg-various-orange'),
    'various-fuchsia': clsx('bg-various-fuchsia'),
    'various-yellow': clsx('bg-various-yellow'),
    'various-rose': clsx('bg-various-rose'),
    'various-cyan': clsx('bg-various-cyan'),
    'various-violet': clsx('bg-various-violet'),
    'various-teal': clsx('bg-various-teal'),
    'various-pink': clsx('bg-various-pink'),
    'various-lime': clsx('bg-various-lime'),
    'various-gray': clsx('bg-various-gray'),
  },
  hoverDark: {
    primary: clsx('hover:bg-neutral-dark'),
    neutral: clsx('hover:bg-neutral-dark'),
    info: clsx('hover:bg-info-dark'),
    positive: clsx('hover:bg-positive-dark'),
    danger: clsx('hover:bg-danger-dark'),
    caution: clsx('hover:bg-caution-dark'),
    surface: clsx('hover:bg-surface-100 hover:dark:bg-surface-inverse'),
    'surface-soft': clsx('hover:bg-surface-light', 'hover:dark:bg-surface-inverse-light'),
    'surface-light': clsx('hover:bg-surface-dark', 'hover:dark:bg-surface-inverse-dark'),
    'surface-dark': clsx('hover:bg-surface-900', 'hover:dark:bg-surface-inverse-900'),
    'various-blue': clsx('hover:bg-various-blue-dark'),
    'various-emerald': clsx('hover:bg-various-emerald-dark'),
    'various-orange': clsx('hover:bg-various-orange-dark'),
    'various-fuchsia': clsx('hover:bg-various-fuchsia-dark'),
    'various-yellow': clsx('hover:bg-various-yellow-dark'),
    'various-rose': clsx('hover:bg-various-rose-dark'),
    'various-cyan': clsx('hover:bg-various-cyan-dark'),
    'various-violet': clsx('hover:bg-various-violet-dark'),
    'various-teal': clsx('hover:bg-various-teal-dark'),
    'various-pink': clsx('hover:bg-various-pink-dark'),
    'various-lime': clsx('hover:bg-various-lime-dark'),
    'various-gray': clsx('hover:bg-various-gray-dark'),
  },
  border: {
    primary: clsx('border-neutral'),
    neutral: clsx('border-neutral'),
    info: clsx('border-info'),
    positive: clsx('border-positive'),
    danger: clsx('border-danger'),
    caution: clsx('border-caution'),
    surface: clsx('border-black/20 dark:border-white/20'),
    inverse: clsx('border-black/10 dark:border-white/60'),
    'various-blue': clsx('border-various-blue'),
    'various-emerald': clsx('border-various-emerald'),
    'various-orange': clsx('border-various-orange'),
    'various-fuchsia': clsx('border-various-fuchsia'),
    'various-yellow': clsx('border-various-yellow'),
    'various-rose': clsx('border-various-rose'),
    'various-cyan': clsx('border-various-cyan'),
    'various-violet': clsx('border-various-violet'),
    'various-teal': clsx('border-various-teal'),
    'various-pink': clsx('border-various-pink'),
    'various-lime': clsx('border-various-lime'),
    'various-gray': clsx('border-various-gray'),
  },
  focusBorder: {
    // primary: clsx('focus:border-neutral-light'),
    // neutral: clsx('focus:border-neutral-light'),
    info: clsx('focus:border-info-light'),
    positive: clsx('focus:border-positive-light'),
    danger: clsx('focus:border-danger-light'),
    caution: clsx('focus:border-caution-light'),
    surface: clsx(''),
    'various-blue': clsx('focus:border-various-blue'),
    'various-emerald': clsx('focus:border-various-emerald'),
    'various-orange': clsx('focus:border-various-orange'),
    'various-fuchsia': clsx('focus:border-various-fuchsia'),
    'various-yellow': clsx('focus:border-various-yellow'),
    'various-rose': clsx('focus:border-various-rose'),
    'various-cyan': clsx('focus:border-various-cyan'),
    'various-violet': clsx('focus:border-various-violet'),
    'various-teal': clsx('focus:border-various-teal'),
    'various-pink': clsx('focus:border-various-pink'),
    'various-lime': clsx('focus:border-various-lime'),
    'various-gray': clsx('focus:border-various-gray'),
  },
  focusRing: {
    primary: clsx(''),
    neutral: clsx(''),
    info: clsx('focus:ring-info-light'),
    positive: clsx('focus:ring-positive-light'),
    danger: clsx('focus:ring-danger-light'),
    caution: clsx('focus:ring-caution-light'),
    surface: clsx('focus:ring-black/10 dark:focus:ring-white/10'),
    'various-blue': clsx('focus:ring-various-blue'),
    'various-emerald': clsx('focus:ring-various-emerald'),
    'various-orange': clsx('focus:ring-various-orange'),
    'various-fuchsia': clsx('focus:ring-various-fuchsia'),
    'various-yellow': clsx('focus:ring-various-yellow'),
    'various-rose': clsx('focus:ring-various-rose'),
    'various-cyan': clsx('focus:ring-various-cyan'),
    'various-violet': clsx('focus:ring-various-violet'),
    'various-teal': clsx('focus:ring-various-teal'),
    'various-pink': clsx('focus:ring-various-pink'),
    'various-lime': clsx('focus:ring-various-lime'),
    'various-gray': clsx('focus:ring-various-gray'),
  },
};

export const colorToTWTokenMap = {
  neutral: 'neutral',
  blue: 'various-blue',
  green: 'various-emerald',
  red: 'various-red',
  yellow: 'various-yellow',
  orange: 'various-orange',
  fuchsia: 'various-fuchsia',
  rose: 'various-rose',
  cyan: 'various-cyan',
  violet: 'various-violet',
  teal: 'various-teal',
  pink: 'various-pink',
  lime: 'various-lime',
  gray: 'various-gray',
};
