export interface PothosBuilderTemplate {
  additionalImports: string;
  ormBody: string;
  ormPlugins: { name: string; from: string }[];
  ormTypings: string;
}
export const pothosBuilderTemplate = `//
// Autogenerated by \`@antribute/backend-cli\`
// Any modifications will be overwritten on subsequent runs.
//

import SchemaBuilder from '@pothos/core';
{{#each ormPlugins}}import {{name}} from '{{from}}';\n{{/each}}
{{additionalImports}}

const builder = new SchemaBuilder<{
  {{ormTypings}}
}>({
  plugins: [{{#each ormPlugins}}{{name}}, {{/each}}],
  {{ormBody}}
});

builder.queryType({});
builder.mutationType({});

export default builder;
`;

export interface PothosSchemaTemplate {
  modules: string[];
}
export const pothosSchemaTemplate = `//
// Autogenerated by \`@antribute/backend-cli\`
// Any modifications will be overwritten on subsequent runs.
//

import builder from './pothos/builder';

{{#each modules}}import '../..{{this}}';{{/each}}

const schema = builder.toSchema();
export default schema;
`;
