export type OrmNoneUtilsTemplate = Record<string, never>;
export const ormNoneUtilsTemplate = `//
// Autogenerated by \`@antribute/backend-cli\`
// This is only generated on first run, so be careful while
// modifying as Antribute Backend requires these exports
//

import type { AuthOptions } from 'next-auth';

export const providers: AuthOptions['providers'] = [
  /* TODO: Add your providers here! */
];
`;

export type OrmPrismaModelTemplate = Record<string, never>;
export const ormPrismaModelTemplate = `//
// Autogenerated by \`@antribute/backend-cli\`
// This is only generated on first run, so be careful while
// modifying as Antribute Backend requires this schema
//

model Account {
  id                String   @id @default(uuid())
  createdAt         DateTime @default(now())
  updatedAt         DateTime @updatedAt
  access_token      String?  @map("accessToken")
  expires_at        Int?     @map("expiresAt")
  id_token          String?  @map("idToken")
  provider          String
  providerAccountId String
  refresh_token     String?  @map("refreshToken")
  scope             String?
  session_state     String?  @map("sessionState")
  token_type        String?  @map("tokenType")
  type              String
  userId            String

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

// We recommend only ever modifying the user model as the rest of these models contain required
// functionality for NextAuth.js
model User {
  id            String       @id @default(uuid())
  accounts      Account[]
  email         String?      @unique
  emailVerified DateTime?
  name          String?
  image         String?      @map("pic")
  sessions      Session[]
}
`;

export type OrmPrismaUtilsTemplate = Record<string, never>;
export const ormPrismaUtilsTemplate = `//
// Autogenerated by \`@antribute/backend-cli\`
// This is only generated on first run, so be careful while
// modifying as Antribute Backend requires these exports
//

import { PrismaAdapter } from '@next-auth/prisma-adapter';
import type { AuthOptions } from 'next-auth';

import { prisma } from '../generated/db';

export const adapter = PrismaAdapter(prisma);
export const callbacks: AuthOptions['callbacks'] = {
  session({ session, user }) {
    return { ...session, user: { ...session.user, id: user.id } };
  },
};
export const providers: AuthOptions['providers'] = [
  /* TODO: Add your providers here! */
];

export const authOptions: AuthOptions = {
  adapter,
  callbacks,
  providers,
};
`;
