name: Build
on:
  - pull_request
jobs:
  build:
    name: Build All Apps, Packages, and Servers
    runs-on: ubuntu-latest
    env:
      # These envs are required for Next.js to build, however they're just empty strings
      AUTH0_FGA_CLIENT_ID: ''
      AUTH0_FGA_CLIENT_SECRET: ''
      AUTH0_FGA_MODEL_ID: ''
      AUTH0_FGA_STORE_ID: ''
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: antribute
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Run Build
        run: pnpm run build
