name: Check Formatting
on: [push]
jobs:
  check-formatting:
    name: Check Repo Formatting with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: antribute/actions/setup@feature/cor-5-create-a-complete-set-of-ci-workflows
      - name: Run Prettier Check
        run: pnpm run style:lint
