name: Chromatic
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  chromatic:
    name: Build Packages and Push Storybook to Chromatic
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Setup
        uses: antribute/actions/setup@feature/cor-5-create-a-complete-set-of-ci-workflows
      - name: Run Build
        run: pnpm run build:packages
      # TODO: We gotta actually create the package before we can publish it to Chromatic lol
      # - name: Publish to Chromatic
      #   uses: chromaui/action@v1
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
