name: Chromatic
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  chromatic:
    name: Build Packages and Push Storybook to Chromatic
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: antribute/actions/setup@main
        with:
          skipCheckout: 'true'
      - name: Run Build
        run: pnpm run build:packages
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          exitZeroOnChanges: true
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: './packages/zephyr-react'
          zip: true
