name: Chromatic
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'packages/zephyr-core/**'
      - 'packages/zephyr-react/**'
jobs:
  chromatic:
    name: Build Packages and Push Storybook to Chromatic
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Build Zephyr
        run: pnpm exec turbo run build --filter=@antribute/zephyr-react
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          exitZeroOnChanges: true
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: './packages/zephyr-react'
          zip: true
