name: 'Pull Request Labeler'
on:
  - pull_request
jobs:
  labeler:
    name: Add Labels to Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
