name: Production Release
on:
  push:
    tags:
      - '**'
jobs:
  release-landing-page:
    if: startsWith(github.ref_name, 'landing-page/')
    name: Release Antribute Landing Page
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Check If Version is Valid
        uses: antribute/actions/check-tag-release@main
        with:
          delimiter: '/'
          pkgPath: './packages/config/package.json'
      - name: Deploy Antribute Landing to Vercel Staging
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STAGING }}
          PRODUCTION: true
      - name: Run E:E Tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./apps/landing-page

  release-configs:
    if: startsWith(github.ref_name, 'config/')
    name: Release Configs Package
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Check If Version is Valid
        uses: antribute/actions/check-tag-release@main
        with:
          delimiter: '/'
          pkgPath: './packages/config/package.json'
      - name: Publish @antribute/config to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          access: 'public'
          dry-run: true # TODO: Remove this once we verify this script works
          package: './packages/config/package.json'
          token: ${{ secrets.NPM_TOKEN }}
  release-zephyr-core:
    if: startsWith(github.ref_name, 'zephyr-core/')
    name: Release Zephyr Core Package
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Check If Version is Valid
        uses: antribute/actions/check-tag-release@main
        with:
          delimiter: '/'
          pkgPath: './packages/zephyr-core/package.json'
      - name: Publish @antribute/config to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          access: 'public'
          package: './packages/zephyr-core/package.json'
          token: ${{ secrets.NPM_TOKEN }}
