name: Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  Test:
    name: Test All Apps, Packages, and Servers
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Run Test
        run: pnpm run test
      - name: Upload Tracking Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/tracking/coverage/cobertura-coverage.xml
          flags: tracking
          fail_ci_if_error: true
      - name: Upload Antribute UI Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/ui/coverage/cobertura-coverage.xml
          flags: ui
          fail_ci_if_error: true
