name: Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  Test:
    name: Test All Apps, Packages, and Servers
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: antribute/actions/setup@main
      - name: Run Test
        run: pnpm run test
      - name: Upload Antribute Landing Page Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./apps/landing-page/coverage/cobertura-coverage.xml
          flags: antribute-landing-page
          fail_ci_if_error: true
      - name: Upload GraphQL Auth0 Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/graphql-auth0/coverage/cobertura-coverage.xml
          flags: graphql-auth0
          fail_ci_if_error: true
      - name: Upload GraphQL Logger Axiom to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/graphql-logger-axiom/coverage/cobertura-coverage.xml
          flags: graphql-logger-axiom
          fail_ci_if_error: true
      - name: Upload GraphQL NextJS Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/graphql-nextjs/coverage/cobertura-coverage.xml
          flags: graphql-nextjs
          fail_ci_if_error: true
      - name: Upload Zephyr React Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/zephyr-react/coverage/cobertura-coverage.xml
          flags: zephyr-react
          fail_ci_if_error: true
